Convert streams and sync to class based
singer-io/tap-intercom pull request #31
Opened 2021-07-20 20:30 UTC by loeakaodas

# Description of change
converting streams and sync to be class based (TDL-13137)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-07-29 15:36 UTC, KAllan357 commented on tests/base.py
> +                self.REPLICATION_METHOD: self.FULL_TABLE,
These have been changed to be full table because the code has been removed that makes them "psuedo-incremental."

2021-07-30 19:40 UTC, KAllan357 requested changes
This looks good other than the changes I asked for regarding changing those streams back to Incremental by saving a bookmark and emitting only the updated rows.

2021-07-30 21:00 UTC, loeakaodas commented on tests/base.py
> +                self.REPLICATION_METHOD: self.FULL_TABLE,
reverted back to INCREMENTAL

2021-08-12 18:39 UTC, KAllan357 approved these changes

2021-08-12 18:40 UTC, merged