Initial commit for request timeouts
singer-io/tap-intercom pull request #36
Opened 2021-11-17 10:35 UTC by prijendev

# Description of change
- Implemented request timeout.
- Added unittest case for the same.
- If config parameter does not pass or pass the value "", "0", 0, "0.0" then set timeout to default value 5min

# Manual QA steps
 - Set small timeout and verify that sync calls are backing off for timeout error.
- Provide timeout in integer, float, and string format and verify that it's used in the request.
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-11-29 06:20 UTC, savan-chovatiya commented on tap_intercom/client.py
> +    @backoff.on_exception(backoff.expo,Timeout, max_tries=5, factor=2) # Backoff for request timeout
```suggestion
    @backoff.on_exception(backoff.expo, Timeout, max_tries=5, factor=2) # Backoff for request timeout
```

2021-11-29 13:54 UTC, savan-chovatiya approved these changes

2021-12-14 06:37 UTC, dbshah1212 commented on .circleci/config.yml
> +            pylint tap_intercom --disable missing-docstring,logging-format-interpolation,no-member,no-self-use,arguments-differ,too-few-public-methods,line-too-long,too-many-arguments,too-many-locals
Was pylint not supported earlier? Why do we need to add so many exceptions?

2021-12-14 06:40 UTC, dbshah1212 commented on tap_intercom/streams.py
> +    # pylint: disable=too-many-arguments,unused-argument
Why it is required here? As you already added in config.yml.

2021-12-14 08:11 UTC, prijendev commented on .circleci/config.yml
> +            pylint tap_intercom --disable missing-docstring,logging-format-interpolation,no-member,no-self-use,arguments-differ,too-few-public-methods,line-too-long,too-many-arguments,too-many-locals
Yes, supported but just added two extra exceptions `consider-using-f-string`(As currently, we are using .format) and `unspecified-encoding` to resolve pylint error. Updated those changes in Makefile instead of `config.yml`

2021-12-14 08:18 UTC, prijendev commented on tap_intercom/streams.py
> +    # pylint: disable=too-many-arguments,unused-argument
No, it is not added config.yml. Instead, we have disabled this error at only two places in the code from where it threw the error. In the existing tap-code, it throws an `unused-argument` pylint `unused-argument` error. Added comment in the code also.

2021-12-14 12:28 UTC, karanpanchal-crest requested changes

2021-12-14 12:28 UTC, karanpanchal-crest commented on tests/unittests/test_request_timeouts.py
> +        self.assertEqual(mocked_get.call_count, 5)
@prijendev Please modularize this code to check the backoff mechanism in a separate file

2021-12-14 13:43 UTC, prijendev commented on tests/unittests/test_request_timeouts.py
> +        self.assertEqual(mocked_get.call_count, 5)
Updated

2021-12-16 04:00 UTC, karanpanchal-crest approved these changes

2021-12-16 18:44 UTC, kspeer825 approved these changes

2021-12-17 05:09 UTC, prijendev commented on .circleci/config.yml
> +            nosetests --with-coverage --cover-erase --cover-package=tap_intercom --cover-html-dir=htmlcov tests/unittests/
Updated tap-tester image to `stitch-tap-tester`

2021-12-21 15:13 UTC, KrisPersonal approved these changes

2021-12-21 15:13 UTC, merged

2025-07-16 17:42 UTC, luandy64 approved these changes