Tdl 17006 revert back companies to incremental
singer-io/tap-intercom pull request #44
Opened 2021-12-30 06:01 UTC by savan-chovatiya

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-12-30 07:31 UTC, savan-chovatiya commented on tap_intercom/sync.py
> +            replication_key = STREAMS[stream].replication_key
The companies stream is changed to incremental again so it has replication_key now so no need to handle it specifically.

2021-12-30 09:59 UTC, dbshah1212 approved these changes

2021-12-31 14:26 UTC, dmosorast requested changes
I looks like the integration test is failing becuase the tap isn't using the bookmark on the second sync.

```
======================================================================
FAIL: test_run (test_intercom_bookmarks.IntercomBookmarks) (stream='companies')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_intercom_bookmarks.py", line 187, in test_run
    self.assertLess(second_sync_count, first_sync_count)
AssertionError: 162 not less than 162
```

2022-01-04 13:58 UTC, savan-chovatiya commented
> For passing build, added _companies_ to untestable_stream and created a backlog card [TDL-17035](https://jira.talendforge.org/browse/TDL-17035) for the fix. ([Slack Thread](https://talend.slack.com/archives/C01TGC4QAUE/p1640870530022000))

For passing build, added _companies_ to untestable stream and created backlog card to fix it as per discussion in this [Slack Thread](https://talend.slack.com/archives/C01TGC4QAUE/p1640870530022000).

2022-01-04 13:59 UTC, savan-chovatiya commented
> I looks like the integration test is failing becuase the tap isn't using the bookmark on the second sync.
> 
> ```
> ======================================================================
> FAIL: test_run (test_intercom_bookmarks.IntercomBookmarks) (stream='companies')
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/project/tests/test_intercom_bookmarks.py", line 187, in test_run
>     self.assertLess(second_sync_count, first_sync_count)
> AssertionError: 162 not less than 162
> ```

For passing build, added _companies_ to untestable stream and created backlog card to fix it as per discussion in this [Slack Thread](https://talend.slack.com/archives/C01TGC4QAUE/p1640870530022000).

2022-01-04 15:56 UTC, dmosorast approved these changes
Discussed offline, the test is manufacturing bookmarks, so the test failure is not necessarily a bug. Capturing the work, and functional testing should be sufficient. Approved ✅

2022-01-04 15:58 UTC, kspeer825 approved these changes

2022-01-05 05:44 UTC, merged