TDL-17017: Fix bookmark for conversation_parts stream.
singer-io/tap-intercom pull request #45
Opened 2021-12-30 10:06 UTC by savan-chovatiya

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-12-30 10:36 UTC, umangagrawal-crest commented on tap_intercom/streams.py
> +        :param state: A dictionary representing singer state which will be preserve during whole sync with passed state
```suggestion
        :param tap_state: A dictionary representing singer state which will be preserve during whole sync with passed state
```

2021-12-30 11:51 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +        :param state: A dictionary representing singer state which will be preserve during whole sync with passed state
Updated

2021-12-30 11:55 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        start_date = singer.get_bookmark(tap_state,
if it's parent's bookmark then please change the name of variable to parent_bookmark

2021-12-30 11:56 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        schema_datetimes = find_datetimes_in_schema(stream_schema)
please provide comment, what it takes

2021-12-30 11:57 UTC, dbshah1212 commented on tap_intercom/streams.py
> +    def sync(self,
do put logger of staring the sync

2021-12-30 11:57 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                counter.increment()
Put info logger with the record count.

2021-12-30 12:23 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +        start_date = singer.get_bookmark(tap_state,
Updated variable name.

2021-12-30 12:24 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +        schema_datetimes = find_datetimes_in_schema(stream_schema)
Added code comments.

2021-12-30 12:24 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +    def sync(self,
Starting sync logger is already there in sync.py

2021-12-30 12:24 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +                counter.increment()
Added logger message with record count.

2021-12-30 12:38 UTC, dbshah1212 approved these changes

2021-12-30 14:24 UTC, dmosorast requested changes

2021-12-30 14:24 UTC, dmosorast commented on tap_intercom/streams.py
> +                                         self.parent.tap_stream_id,
This approach isn't in line with our best practices. All streams should bookmark independently. State dependencies like this cause code that is very hard to read and maintain (as seen with the duplicate concept of "tap_state" versus "state" here).

So, the `conversation_parts` will need a custom sync method regardless of its approach so it can make its own way through the parent stream and store its own bookmarks as it needs.

Additionally, the parent should be rather low volume (I'd expect below 100k), so any optimization gained from this approach is lost in code complexity.

2021-12-30 14:24 UTC, dmosorast commented on tap_intercom/streams.py
> +class ConversationParts(FullTableStream):
As a design consideration, this stream is a sort of custom concept, and I'd expect that it can probably inherit directly from the BaseStream class to do its custom bookmarking independent of the other more straightforward sync logic.

I would also still call this an incremental stream, as it bookmarks on it's parent's replication key. This approach is just a more coarse grained incremental extraction, but it's closer to incremental than full table. It was mislabeled as full table in the past which caused this confusion in the first place.

2021-12-31 04:56 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +                },
An updated search query for conversation stream to consider records greater or equal to bookmark from API as same as v1.3.3.

2021-12-31 07:01 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +class ConversationParts(FullTableStream):
We updated conversation_parts sync as per suggestion. Inherited ConversationParts from BaseStream and kept it incremental by writing a custom sync which will bookmark on its parent replication key.

2021-12-31 09:10 UTC, dbshah1212 approved these changes

2021-12-31 14:13 UTC, dmosorast requested changes
Just a few minor changes and cleanup, I think overall this looks good.

2021-12-31 14:13 UTC, dmosorast commented on tap_intercom/streams.py
> +            replication_key = self.epoch_milliseconds_to_dt_str(record[self.parent.replication_key] * 1000)
Minor naming, this should probably be called `parent_bookmark_value` instead of `replication_key`

2021-12-31 14:13 UTC, dmosorast commented on tap_intercom/streams.py
> +            LOGGER.info("Stream: {}, updating bookmark: {}".format(self.tap_stream_id, replication_key))
I think this log line can be removed. It will likely be very noisy with less added benefit. In Stitch, there will always be a state diff log that occurs when the state gets successfully saved into the system, and for traceability, that's usually more helpful than the tap logging when it updated state.

2021-12-31 14:30 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +            new_dttm = transformer._transform_datetime(timestamp)
Updated it to `transform.unix_milliseconds_to_datetime` directly.

2021-12-31 14:30 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +        The sync logic for an full table stream.
Updated docstring by making it specific to conversation_parts.

2021-12-31 14:31 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +            replication_key = self.epoch_milliseconds_to_dt_str(record[self.parent.replication_key] * 1000)
Updated `replication_key` with `parent_bookmark_value`.

2021-12-31 14:31 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +            LOGGER.info("Stream: {}, updating bookmark: {}".format(self.tap_stream_id, replication_key))
Removed logger line as per suggestion.

2021-12-31 14:39 UTC, dmosorast approved these changes
Looks good to me!

2022-01-03 06:05 UTC, umangagrawal-crest approved these changes

2022-01-05 05:42 UTC, merged