TDL-17002: Make the logger messages more descriptive
singer-io/tap-intercom pull request #46
Opened 2021-12-30 12:59 UTC by harshpatel4crest

# Description of change
TDL-17002: Make the logger messages more descriptive

- Added logger messages

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-12-30 13:04 UTC, dbshah1212 commented on tap_intercom/streams.py
> -            records = transform_json(response, self.tap_stream_id, self.data_key)
Why do we remove this?

2021-12-30 13:09 UTC, harshpatel4crest commented on tap_intercom/streams.py
> -            records = transform_json(response, self.tap_stream_id, self.data_key)
We did not remove, just shifted above the condition as it contains the records, we can print the logger containing number of records and then the logger of **"Syncing next page"**

2021-12-31 10:30 UTC, dbshah1212 approved these changes

2021-12-31 14:24 UTC, KrisPersonal approved these changes

2021-12-31 14:37 UTC, dmosorast requested changes

2021-12-31 14:37 UTC, dmosorast commented on tap_intercom/streams.py
> +            LOGGER.info("Synced: {}, parent_id: {}, records: {}".format(self.tap_stream_id, record, 1))
Same thing here as in AdminList. This can just be treated as a regular full table stream for logging purposes and simply log a full record count at the end of the sync call. This log line in particular seems too verbose since it's a 1-to-1 mapping, the tap will just end up logging every record's ID.

2021-12-31 14:37 UTC, dmosorast commented on tap_intercom/streams.py
> +        LOGGER.info("Synced: {}, records: {}".format(self.tap_stream_id, len(response.get(self.data_key, []))))
I think the log lines for this class aren't necessary, since this "stream" is just an implementation detail of the `Admins` stream. It is not selectable by the user, so treating the `Admins` stream just as a regular full table stream should be sufficient.

2021-12-31 14:59 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +            LOGGER.info("Synced: {}, parent_id: {}, records: {}".format(self.tap_stream_id, record, 1))
@dmosorast Removed the logger.

2021-12-31 14:59 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        LOGGER.info("Synced: {}, records: {}".format(self.tap_stream_id, len(response.get(self.data_key, []))))
@dmosorast Removed the logger.

2021-12-31 15:45 UTC, dmosorast requested changes

2021-12-31 15:45 UTC, dmosorast commented on tap_intercom/streams.py
> +            LOGGER.info("Syncing: {}, parent_stream: {}, parent_id: {}".format(self.tap_stream_id, self.parent.tap_stream_id, record))
This one can be removed as well because it will be too verbose.

2021-12-31 15:45 UTC, dmosorast commented on tap_intercom/streams.py
> +        LOGGER.info("Syncing: {}".format(self.tap_stream_id))
This log line shouldn't appear in this class since it isn't a selectable stream.

Can you move it to the first line of `Admins.get_records`?

2022-01-03 06:05 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +            LOGGER.info("Syncing: {}, parent_stream: {}, parent_id: {}".format(self.tap_stream_id, self.parent.tap_stream_id, record))
Removed the logger.

2022-01-03 06:05 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        LOGGER.info("Syncing: {}".format(self.tap_stream_id))
Moved the logger to the first line of **Admins.get_records**

2022-01-04 14:03 UTC, dmosorast requested changes

2022-01-04 14:03 UTC, dmosorast commented on tap_intercom/streams.py
> +        LOGGER.info("Syncing: {}".format(self.parent.tap_stream_id))
This should be `self.tap_stream_id` instead of `self.parent.tap_stream_id`. Apologies for being so particular, but these kinds of log lines can cause a large amount of confusion.

2022-01-04 14:31 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        LOGGER.info("Syncing: {}".format(self.parent.tap_stream_id))
Updated to **self.tap_stream_id**

2022-01-04 14:37 UTC, dmosorast approved these changes

2022-01-05 06:14 UTC, merged