TDL-18800 : Transformation issue
singer-io/tap-intercom pull request #52
Opened 2022-05-09 21:44 UTC by shantanu73

# Description of change
Resolved transform issue due to changes in schema of remote_created_at in companies.json

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-05-10 12:58 UTC, shantanu73 commented on tap_intercom/schemas/companies.json
> +      "type": ["null", "integer", "string"],
@KrisPersonal Added integer as the field "remote_created_at" is having integer values when a GET API call is made to url "https://api.intercom.io/companies/scroll" example data :-
`            "name": "Overlogy",
            "remote_created_at": 1552971992,
            "created_at": 1552957595,
            "updated_at": 1555632355,
            "last_request_at": 1552957595,
            "monthly_spend": 0,
`

2022-05-27 08:37 UTC, RushT007 requested changes
Add assertion to check first sync and second sync respects the start date.

2022-05-27 13:48 UTC, kspeer825 requested changes

2022-05-27 13:48 UTC, kspeer825 commented on tests/base.py
> +    DIFF = 2
Why are there 2 variables for setting the start date? Couldn't this jus be like `DAYS = 12`

2022-05-27 13:48 UTC, kspeer825 commented on tests/test_intercom_bookmarks.py
> +                    self.LOGGER.info(msg=f"Skipping test case since no messages are found in First Sync for stream {stream}")
Instead of using the singer logger (defined in base.py) please use the tap-tester logger. Can be imported as `from tap-tester.logger import LOGGER`.

2022-05-27 13:48 UTC, kspeer825 commented on tests/test_intercom_bookmarks.py
> +                    continue
If a stream cannot be covered reliably e.g. records are not consistently replicated for a test scenario, they should not be included. This pattern reduces confidence in the test. Unstable streams should be covered in a separate test scenarios targeting a specific point in time where we know tests data exists. If that cannot be done then I don't think the stream can be tested in automation.

2022-05-27 13:48 UTC, kspeer825 commented on tests/test_intercom_start_date.py
> +                self.assertGreaterEqual(record_count_sync_1, record_count_sync_2)
Can this just be assertGreater?

2022-05-27 17:19 UTC, shantanu73 commented on tests/test_intercom_bookmarks.py
> +                    self.LOGGER.info(msg=f"Skipping test case since no messages are found in First Sync for stream {stream}")
I'll use tap-tester logger. Will update in next commit.

2022-05-27 17:21 UTC, shantanu73 commented on tests/base.py
> +    DIFF = 2
I'll change this to one variable only.
I kept it to 2 variables as I observed there were 2 different values for start date configured in base.py.
But, I'll change it to single variable.

2022-05-27 17:27 UTC, shantanu73 commented on tests/test_intercom_start_date.py
> +                self.assertGreaterEqual(record_count_sync_1, record_count_sync_2)
Yeah, that makes more sense.

2022-05-27 17:28 UTC, shantanu73 commented
> Add assertion to check first sync and second sync respects the start date.

Will make that change.

2022-06-01 05:51 UTC, shantanu73 commented on tests/test_intercom_start_date.py
> +                self.assertGreaterEqual(record_count_sync_1, record_count_sync_2)
@kspeer825 
For streams with Full Table replication, all records get synced for Sync-1 & Sync-2.
Hence, we need to keep it assertGreaterEqual.

2022-06-01 05:53 UTC, shantanu73 commented on tests/test_intercom_bookmarks.py
> +                    continue
@kspeer825 For the time being, we can move ahead with this approach, we can create another ticket to fix unstable streams. We're blocked on this tap for quite sometime.
@KrisPersonal thoughts?

2022-06-01 15:00 UTC, KrisPersonal approved these changes

2022-06-08 13:14 UTC, kspeer825 commented on tests/test_intercom_bookmarks.py
> +                    continue
I think this should be removed, and the skip on line 149-151

2022-06-08 13:26 UTC, kspeer825 approved these changes

2022-06-08 14:14 UTC, shantanu73 commented on tests/test_intercom_bookmarks.py
> +                    continue
Yes, Resolved it.

2022-06-08 14:34 UTC, RushT007 approved these changes

2022-06-08 15:01 UTC, merged