TDL-19859: Upgrade API version and related new fields
singer-io/tap-intercom pull request #53
Opened 2022-07-13 05:44 UTC by harshpatel4crest

# Description of change
TDL-19859: Upgrade API version and related new fields
- Upgraded API latest version: 2.5
- Added missing fields as per the [stability analysis slides](https://docs.google.com/presentation/d/1bFJHx0NEEh7viscimJP7YrloWSrrFowGMEyTEBrnqkk/edit#slide=id.g10968146cf7_2_75).

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-07-25 10:43 UTC, dbshah1212 approved these changes

2022-07-26 10:21 UTC, savan-chovatiya approved these changes

2022-08-02 08:11 UTC, shantanu73 approved these changes

2022-08-03 17:36 UTC, RushiT0122 approved these changes

2022-08-03 17:38 UTC, kspeer825 requested changes
This tap does not have an all fields tap-tester test. Could you add it as part of this change? If it blows up the scope of this ticket too much, then could you create a new backlog ticket for the test?

2022-08-08 06:00 UTC, harshpatel4crest commented
> This tap does not have an all fields tap-tester test. Could you add it as part of this change? If it blows up the scope of this ticket too much, then could you create a new backlog ticket for the test?

Added all_fields tap-tester test.

2022-08-19 06:58 UTC, RushiT0122 approved these changes

2022-08-19 18:35 UTC, kspeer825 approved these changes

2022-09-26 07:57 UTC, merged