TDL-19892: Use common API calls for parent's data for parent/child streams
singer-io/tap-intercom pull request #55
Opened 2022-07-15 07:04 UTC by harshpatel4crest

# Description of change
TDL-19892: Use common API calls for parent's data for parent/child streams
- Updated the code to use common API calls for parent-child streams.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-07-25 11:49 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +                start_date = min(singer.utils.strptime_to_utc(parent_bookmark), singer.utils.strptime_to_utc(child_bookmark))
Change variable name here. This name is confusing in the later part with the `start_date` of config.

2022-07-25 11:52 UTC, savan-chovatiya commented on tap_intercom/sync.py
> +                continue
Add a code comment here regarding the `continue` statement

2022-07-25 11:53 UTC, savan-chovatiya commented on tests/unittests/test_conversation_part_bookmarks.py
> +            {"id": 2, "updated_at": 1640637000000}  # UTC datetime "2021-12-27T20:30:00.000000Z" for 1640637000
The API call is the same as before so any reason to update the `updated_at` field's mock values?

2022-07-25 11:57 UTC, dbshah1212 commented on tap_intercom/sync.py
> +            selected_streams.append(catalog.get_stream(parent_stream))
Adding parents into the selected stream is not the right thing to do, because we are not gonna write the parent's records. Create a separate list of sync_to_stream and inside that, you should add these parents.

2022-07-25 11:58 UTC, savan-chovatiya commented on tests/unittests/test_parent_child_sync.py
> +class Schema:
The `Schema` mock class is already defined in `test_conversation_part_bookmarks.py` so please import it and use it.

2022-07-25 11:59 UTC, savan-chovatiya commented on tests/unittests/test_parent_child_sync.py
> +class Catalog:
The `Stream` and `Catalog` mock classes are already defined in `test_conversation_part_bookmarks.py` so please import it and use it.

2022-07-25 11:59 UTC, dbshah1212 commented on tap_intercom/sync.py
> +    # loop over the parent-child stream and add parent stream to sync if child stream is selected and parent stream is not selected
```suggestion
    # Loop over the parent-child stream and add the parent stream to sync if the child stream is selected and the parent stream is not selected
```

2022-07-25 12:00 UTC, dbshah1212 commented on tap_intercom/sync.py
> +        selected_stream_names.append(stream.stream)
Why we are not adding `stream.tap_stream_id`?

2022-07-25 12:02 UTC, savan-chovatiya commented on tests/unittests/test_parent_child_sync.py
> +        ['child_selected_state', [['conversation_parts'], {'bookmarks': {'conversation_parts': {'updated_at': '2021-01-02'}, 'conversations': {'updated_at': '2021-01-03'}}}], '2021-01-02'],
Divide long lines into multiline for better readability.

2022-07-25 12:07 UTC, savan-chovatiya commented on tests/unittests/test_parent_child_sync.py
> +    def test_sync(self, name, test_data, expected_data, mocked_sync):
Give a more explanatory test case name.

2022-07-25 12:07 UTC, savan-chovatiya commented on tests/unittests/test_parent_child_sync.py
> +    def test_syncing(self, name, test_data, expected_data, mocked_get_records, mocked_write_schema):
Give a more explanatory test case name.

2022-07-25 12:17 UTC, dbshah1212 commented on tap_intercom/sync.py
> +from tap_intercom.streams import STREAMS, CHILD_STREAMS
Why do we require CHILD_STREAMS dict, we can define them in stream class?

2022-07-25 12:20 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                # sync child stream, if child is selected
```suggestion
                # Sync child stream, if the child is selected
```

2022-07-25 12:21 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                # write record if parent is selected
```suggestion
                # Write record if a parent is selected
```

2022-07-25 12:22 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                # write schema for child stream as it will be synced by the parent stream
```suggestion
                # Write schema for child stream as it will be synced by the parent stream
```

2022-07-25 12:22 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                # write schema for child stream as it will be synced by the parent stream
Make first latter capital.

2022-07-25 12:22 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        # if the current stream has child stream, then get the child stream's bookmark and
```suggestion
        # If the current stream has a child stream, then get the child stream's bookmark and
```

2022-07-26 09:19 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        # if the current stream has child stream, then get the child stream's bookmark and
Updated comments.

2022-07-26 09:19 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                # write schema for child stream as it will be synced by the parent stream
Updated comment.

2022-07-26 09:22 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                # sync child stream, if child is selected
Updated the comment.

2022-07-26 09:50 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +from tap_intercom.streams import STREAMS, CHILD_STREAMS
Yes, we can define it in the stream's class, but it will become easy to loop on CHILD_STREAMS rather than STREAMS for preparing the `streams_to_sync` list in the sync.py file.

2022-07-26 09:51 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +class TestParentChildWriteRecords(unittest.TestCase):
Added unittest for the condition.

2022-07-26 09:51 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +    def test_syncing(self, name, test_data, expected_data, mocked_get_records, mocked_write_schema):
Updated the test case name.

2022-07-26 09:51 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +    def test_sync(self, name, test_data, expected_data, mocked_sync):
Updated the test case name.

2022-07-26 09:51 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +        ['child_selected_state', [['conversation_parts'], {'bookmarks': {'conversation_parts': {'updated_at': '2021-01-02'}, 'conversations': {'updated_at': '2021-01-03'}}}], '2021-01-02'],
Updated.

2022-07-26 09:52 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +        selected_stream_names.append(stream.stream)
Most of the time tap_stream_id and stream will have the same values. Updated the current code to use tap_stream_id.

2022-07-26 09:52 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +    # loop over the parent-child stream and add parent stream to sync if child stream is selected and parent stream is not selected
Updated the comment.

2022-07-26 09:53 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +class Catalog:
Used the already defined mock Catalog class.

2022-07-26 09:53 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +class Schema:
Updated the test case.

2022-07-26 09:53 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +            selected_streams.append(catalog.get_stream(parent_stream))
Updated the code to add extra streams to sync in `streams_to_sync`.

2022-07-26 09:54 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +                continue
Added comment.

2022-07-26 09:54 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                start_date = min(singer.utils.strptime_to_utc(parent_bookmark), singer.utils.strptime_to_utc(child_bookmark))
Updated the variable name.

2022-07-26 10:05 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                # write record if parent is selected
Updated comment.

2022-07-26 10:28 UTC, harshpatel4crest commented on tests/unittests/test_conversation_part_bookmarks.py
> +            {"id": 2, "updated_at": 1640637000000}  # UTC datetime "2021-12-27T20:30:00.000000Z" for 1640637000
The code will now go through `transform_times` when syncing conversation_parts, as a result, the parent's replication key will be in millisecond format.

2022-08-02 13:28 UTC, savan-chovatiya approved these changes

2022-08-03 09:57 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        # check if the current stream has child stream or not
Make the first latter of the sentence Capital for each comment.

2022-08-03 09:59 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        has_child = self.tap_stream_id in CHILD_STREAMS
Remove CHILD_STREAMS dict, we can handle it using parent and child classes.

2022-08-03 10:04 UTC, dbshah1212 commented on tap_intercom/streams.py
> +CHILD_STREAMS = {
handle it using classes.

2022-08-05 04:44 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        # check if the current stream has child stream or not
Updated comments.

2022-08-05 04:44 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        has_child = self.tap_stream_id in CHILD_STREAMS
Updated the code.

2022-08-05 04:44 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +CHILD_STREAMS = {
Updated.

2022-08-05 05:26 UTC, dbshah1212 commented on tap_intercom/sync.py
> +from tap_intercom.streams import STREAMS, CHILD_STREAMS
We shoud include the selected streams in streams_to_sync so run a loop on streams and check if stream is selected or child stream of it is selected then add that stream in streams_to_sync.

2022-08-05 06:39 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +from tap_intercom.streams import STREAMS, CHILD_STREAMS
We are looping in the selected streams to use the shuffling functionality of singer-python for interrupted syncs and adding the independent streams and parent stream in **streams_to_sync**

2022-08-05 06:41 UTC, dbshah1212 commented on tap_intercom/streams.py
>          """
get_parent_data method called only once and it doesn't make sense as part of the parent-child we are restricting parent call to once, so can we remove this or move this to the appropriate class?

2022-08-05 06:50 UTC, dbshah1212 commented on tap_intercom/streams.py
>      parent = AdminList
Why child var is not defined for `AdminList`? We should call Admins in `AdminList` calls, not the reverse one.

2022-08-05 06:51 UTC, dbshah1212 commented on tap_intercom/streams.py
>      parent = AdminList
If it is scenario at other place then also update it.

2022-08-05 07:46 UTC, harshpatel4crest commented on tap_intercom/streams.py
>      parent = AdminList
The AdminList and Admin are parent-child streams, but the **admin** is written in the catalog but the admin_list is not. The purpose of admin_list is to return a list of admins through which individual admins will be synced.

2022-08-05 08:50 UTC, dbshah1212 commented on tap_intercom/streams.py
>      parent = AdminList
Can you mention the same in the comment?

2022-08-05 09:14 UTC, harshpatel4crest commented on tap_intercom/streams.py
>      parent = AdminList
Added comment in sync.py file.

2022-08-08 07:06 UTC, dbshah1212 approved these changes

2022-08-19 05:49 UTC, RushiT0122 commented on tap_intercom/streams.py
> +                return state
Is this else block redundant since sync is called when parent or child is selected so either of above 3 conditions will be true?

2022-08-19 06:03 UTC, RushiT0122 commented on tap_intercom/sync.py
> +            # The AdminList and Admin are parent-child streams, the admin is written in the catalog but the admin_list is not.
Correction: # The AdminList and Admin are parent-child streams, the `admins` is written in the catalog but the admin_list is not.

2022-08-19 06:33 UTC, RushiT0122 requested changes

2022-08-19 06:33 UTC, RushiT0122 commented on tests/unittests/test_conversation_part_bookmarks.py
> +        state = {'bookmarks': {'conversation_parts': {'updated_at': '2021-12-27T20:30:00.000000Z'}, 'conversations': {'updated_at': '2021-12-27T20:30:00.000000Z'}}}
```suggestion
        state = {'bookmarks': {'conversation_parts': {'updated_at': '2021-12-27T20:30:00.000000Z'},
                               'conversations': {'updated_at': '2021-12-27T20:30:00.000000Z'}}}
```

2022-08-19 06:33 UTC, RushiT0122 commented on tests/unittests/test_conversation_part_bookmarks.py
> +        conversation_part = Conversations(client, Catalog(['conversations', 'conversation_parts']), ['conversations', 'conversation_parts'])
```suggestion
        conversation_part = Conversations(client=client, 
                                            catalog=Catalog(['conversations', 'conversation_parts']), 
                                            selected_streams=['conversations', 'conversation_parts'])
```

2022-08-19 06:33 UTC, RushiT0122 commented on tests/unittests/test_parent_child_sync.py
> +        conversations = Conversations(client, Catalog(test_data[0]), test_data[0])
```suggestion
        conversations = Conversations(client=client, catalog=Catalog(test_data[0]), selected_streams=test_data[0])
```

2022-08-19 06:33 UTC, RushiT0122 commented on tests/unittests/test_parent_child_sync.py
> +        conversations.sync(state, {}, {}, config, None)
```suggestion
        conversations.sync(state=state, stream_schema={}, stream_metadata={}, config=config, transformer=None)
```

This will give better readability.

2022-08-19 06:33 UTC, RushiT0122 commented on tests/unittests/test_parent_child_sync.py
> +        conversations.sync({}, {}, {}, config, None)
```suggestion
        conversations = Conversations(client=client, catalog=Catalog(['conversations']), selected_streams=['conversations'])
        config = {'start_date': '2021-01-01'}
        conversations.sync(state={}, stream_schema={}, stream_metadata={}, config=config, transformer=None)
```
For better readability.

2022-08-22 05:27 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                return state
Yes, the Tap will not go into the else condition.

2022-08-22 05:29 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +        conversations.sync({}, {}, {}, config, None)
Updated as per suggestion.

2022-08-22 05:29 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +        conversations.sync(state, {}, {}, config, None)
Updated the code.

2022-08-22 05:29 UTC, harshpatel4crest commented on tests/unittests/test_parent_child_sync.py
> +        conversations = Conversations(client, Catalog(test_data[0]), test_data[0])
Updated.

2022-08-22 05:29 UTC, harshpatel4crest commented on tests/unittests/test_conversation_part_bookmarks.py
> +        conversation_part = Conversations(client, Catalog(['conversations', 'conversation_parts']), ['conversations', 'conversation_parts'])
Updated.

2022-08-22 05:30 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +            # The AdminList and Admin are parent-child streams, the admin is written in the catalog but the admin_list is not.
Updated the comment.

2022-09-06 18:57 UTC, RushiT0122 requested changes

2022-09-06 18:57 UTC, RushiT0122 commented on tests/unittests/test_conversation_part_bookmarks.py
> +        conversation_part = Conversations(client, Catalog(['conversations', 'conversation_parts']), ['conversations', 'conversation_parts'])
I can't see the changes been made.

2022-09-06 18:57 UTC, RushiT0122 commented on tests/unittests/test_parent_child_sync.py
> +        conversations = Conversations(client, Catalog(test_data[0]), test_data[0])
I can't see the changes been made.

2022-09-06 18:57 UTC, RushiT0122 commented on tests/unittests/test_parent_child_sync.py
> +        conversations.sync(state, {}, {}, config, None)
I can't see the changes been made.

2022-09-07 06:01 UTC, harshpatel4crest commented
@RushiT0122 I have already made the suggested changes in unittests for argument passing.
Reference: https://github.com/singer-io/tap-intercom/pull/55/files#diff-6fe7cea6821dd5f9f6c736a26c7a59510fae9cc9e515c5818343c63c587d5dc0R57 and https://github.com/singer-io/tap-intercom/pull/55/files#diff-98d50c077e9f69b95074f17c78efecc96760893b122bde89e3da1758e8ef025bR52

2022-09-07 06:11 UTC, harshpatel4crest commented on tap_intercom/sync.py
> +        Get streams to sync ie. selected streams and parent stream if child stream stream or parent stream is selected
Updated comment.

2022-09-07 06:12 UTC, harshpatel4crest commented
@RushiT0122 Removed redundant code for returning state when parent and child streams are not selected.

2022-09-13 08:39 UTC, RushiT0122 approved these changes

2022-09-14 18:55 UTC, kspeer825 requested changes
The current implementation of the bookmarks test for tap-intercom is invalid. It combines the standard tap-tester start date and bookmarks tests. It is not actually providing coverage and needs to be addressed for this change .

Also this change should have a tap-tester test that performs syncs for the following scenario:
 - child bookmark is earlier than parent bookmark
 - parent bookmark is earlier than child bookmark
 and should assert that:
 - in both cases the earlier bookmark is used by looking at the replicated records.
 - in both cases records between the bookmark values are replicated.

2022-09-15 17:34 UTC, harshpatel4crest commented
> The current implementation of the bookmarks test for tap-intercom is invalid. It combines the standard tap-tester start date and bookmarks tests. It is not actually providing coverage and needs to be addressed for this change .
> 
> Also this change should have a tap-tester test that performs syncs for the following scenario:
> 
> * child bookmark is earlier than parent bookmark
> * parent bookmark is earlier than child bookmark
>   and should assert that:
> * in both cases the earlier bookmark is used by looking at the replicated records.
> * in both cases records between the bookmark values are replicated.

Thanks, @kspeer825 for the suggestion. We updated the bookmark test. As we are writing the parent's replication key in the child stream's bookmark, so we have skipped the conversation_parts(child stream) but we have included conversations(parent) in the current bookmark test case by setting the dynamic start date as the stream was being skipped earlier due to more data.

We are collecting data from minimum bookmarks out of parent-child streams, but tap will only write data that is greater than the bookmark for the parent stream and all the child for the parent greater than the child's bookmark. The final output of the tap will remain the same after this change.
We added a new integration test for the scenario mentioned above. We will also make sure to add this test in all the taps from now onwards.

2022-09-26 11:38 UTC, merged

2025-07-10 19:16 UTC, luandy64 approved these changes