TDL-19860: Need to update Primary keys for Company_Attributes & Contacts streams
singer-io/tap-intercom pull request #56
Opened 2022-07-19 07:04 UTC by harshpatel4crest

# Description of change
TDL-19860: Need to update Primary keys for Company_Attributes & Contacts streams
- Updated the Primary Key for `company_attributes` and used the hash of `['id', 'name', 'description']` as the Primary Key.
**NOTE:** The `contact_attributes` is also using the same endpoint as the `company_attributes` thus, updated the Primary Key for contact_attributes as well.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-07-26 09:43 UTC, savan-chovatiya requested changes

2022-07-26 09:43 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +                hash_string += str(original_record.get(key, ''))
```suggestion
        for key in fields_to_hash:
                hash_string += str(original_record.get(key, ''))
```

2022-07-26 09:43 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +                    record = self.generate_record_hash(record)
Add code comment

2022-07-26 09:43 UTC, savan-chovatiya commented on tap_intercom/streams.py
> +        return super().sync(state, stream_schema, stream_metadata, config, transformer, sync_with_version = True)
Remove this function and define one class attribute in the base class as `sync_with_version = False`, and override it with `sync_with_version  = True` for 2 streams.

2022-07-26 09:43 UTC, savan-chovatiya commented on tests/unittests/test_sdc_record_hash.py
> +    def test_generate_hash(self, name, test_data):
Add doc string for all unit test cases.

2022-07-26 11:03 UTC, dbshah1212 commented on tap_intercom/streams.py
> +        # -> Default: As discussed with support, there is 'id' for custom data_attributes and ther will be unique
```suggestion
        # -> Default: As discussed with support, there is an 'id' for custom data_attributes and that will be unique
```

2022-07-26 11:11 UTC, dbshah1212 commented on tap_intercom/streams.py
> +                    # Using "write_message" if the version is found as, "write_record" params does not contain "version"
```suggestion
                    # Using "write_message" if the version is found. As "write_record" params do not contain "version"
```

2022-07-26 11:28 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                    # Using "write_message" if the version is found as, "write_record" params does not contain "version"
Updated the comment.

2022-07-26 11:28 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        # -> Default: As discussed with support, there is 'id' for custom data_attributes and ther will be unique
Updated the comment.

2022-07-26 11:28 UTC, harshpatel4crest commented on tests/unittests/test_sdc_record_hash.py
> +    def test_generate_hash(self, name, test_data):
Added function comment for the tests.

2022-07-26 11:29 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +        return super().sync(state, stream_schema, stream_metadata, config, transformer, sync_with_version = True)
Updated the code with the suggested approach.

2022-07-26 11:29 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                    record = self.generate_record_hash(record)
Added comment.

2022-07-26 11:29 UTC, harshpatel4crest commented on tap_intercom/streams.py
> +                hash_string += str(original_record.get(key, ''))
Updated the code.

2022-07-26 11:33 UTC, savan-chovatiya approved these changes

2022-08-03 10:25 UTC, dbshah1212 approved these changes

2022-08-18 18:29 UTC, RushiT0122 commented on tests/test_intercom_automated_fields.py
Standard assertions missing for automatic fields.

2022-08-18 18:43 UTC, RushiT0122 requested changes
Standard assertions missing from automatic fields integration test.

2022-08-22 05:50 UTC, harshpatel4crest commented
> Standard assertions missing from automatic fields integration test.

@RushiT0122 They are added as part for PR #57

2022-08-24 05:15 UTC, umangagrawal-crest requested changes
Please update README file

2022-08-25 05:28 UTC, savan-chovatiya approved these changes

2022-08-25 05:37 UTC, harshpatel4crest commented
> Please update README file

Updated README file.

2022-09-06 16:08 UTC, RushiT0122 commented on tests/test_intercom_automated_fields.py
> +                record_messages_keys = [set(row.get('data').keys()) for row in data.get('messages', {})
- Name of test file should be `test_intercom_automatic_fields.py`
- Assertion missing `Verify that all replicated records have unique primary key values.`
- Doc string should be fixed

2022-09-06 16:15 UTC, RushiT0122 requested changes
Requested changes in integration test

2022-09-07 10:00 UTC, harshpatel4crest commented on tests/test_intercom_automated_fields.py
> +                record_messages_keys = [set(row.get('data').keys()) for row in data.get('messages', {})
They are covered as part of Tap-Tester tests PR #57

2022-09-13 08:54 UTC, RushiT0122 approved these changes

2022-09-26 07:46 UTC, merged

2025-07-16 17:42 UTC, luandy64 approved these changes