TDl-9845: Add missing tap tester & unit tests
singer-io/tap-intercom pull request #57
Opened 2022-07-29 08:54 UTC by savan-chovatiya

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-08-01 12:35 UTC, harshpatel4crest commented on tests/base.py
> +    DATETIME_FMT = {
We can remove this if it is not used.

2022-08-01 12:43 UTC, harshpatel4crest commented on tests/test_intercom_start_date.py
> +                if expected_metadata[self.REPLICATION_METHOD] == self.INCREMENTAL:
Please add the `OBEYS_START_DATE` key in `expected_metadata` and use it here.

2022-08-02 12:14 UTC, savan-chovatiya commented on tests/base.py
> +    DATETIME_FMT = {
Removed `DATETIME_FMT ` as it was not used anywhere.

2022-08-02 12:14 UTC, savan-chovatiya commented on tests/test_intercom_start_date.py
> +                if expected_metadata[self.REPLICATION_METHOD] == self.INCREMENTAL:
Added `OBEYS_START_DATE` and used it in the start_date test.

2022-08-02 12:42 UTC, harshpatel4crest approved these changes

2022-08-04 09:56 UTC, dbshah1212 commented on tests/base.py
> +        """convert datetime with a format to timestamp"""
```suggestion
        """Convert datetime with a format to timestamp"""
```

2022-08-04 09:57 UTC, dbshah1212 commented on tests/test_intercom_interrupted_sync.py
> +            Assertion Method that verifies a string value is a formatted datetime with
```suggestion
            Assertion method that verifies a string value is a formatted datetime with
```

2022-08-04 09:58 UTC, dbshah1212 commented on tests/test_intercom_interrupted_sync.py
> +            _ = dt.strptime(value, str_format)
Use the meaningful variable name, f we are not using this further then no need to do the assignment.

2022-08-05 09:42 UTC, savan-chovatiya commented on tests/base.py
> +        """convert datetime with a format to timestamp"""
Updated comment.

2022-08-05 09:42 UTC, savan-chovatiya commented on tests/test_intercom_interrupted_sync.py
> +            Assertion Method that verifies a string value is a formatted datetime with
Updated comment.

2022-08-05 09:42 UTC, savan-chovatiya commented on tests/test_intercom_interrupted_sync.py
> +            _ = dt.strptime(value, str_format)
Removed assignment.

2022-08-08 06:11 UTC, dbshah1212 approved these changes

2022-08-17 20:28 UTC, kspeer825 requested changes

2022-08-17 20:28 UTC, kspeer825 commented on tests/test_intercom_pagination.py
> +                # Verify by private keys that data is unique for page
If there are more than 2 pages of data for a stream could you add logic to ensure uniqueness across all pages instead of just the first 2? See reference here https://github.com/singer-io/tap-mixpanel/blob/2cf3a86231da042f76f4e3ef9fa8c23600b6f593/tests/tap_tester/test_all_fields_pagination.py#L134-L153

2022-08-17 20:28 UTC, kspeer825 commented on tests/test_intercom_interrupted_sync.py
> +                            interrupted_bookmark_datetime = start_date_datetime
I don't think this conditional logic is appropriate in this state. We should purposefully set bookmakrk in state for the interrupted stream and prove that the tap picks up records only from that point onward.

2022-08-17 20:28 UTC, kspeer825 commented on tests/test_intercom_interrupted_sync.py
> +                    for rec in interrupted_records:
I don't think any of the streams under test are Full Table.

2022-08-18 06:55 UTC, harshpatel4crest commented on tests/test_intercom_pagination.py
> +                # Verify by private keys that data is unique for page
Updated the pagination test case to verify uniqueness among all pages.

2022-08-18 06:56 UTC, harshpatel4crest commented on tests/test_intercom_interrupted_sync.py
> +                    for rec in interrupted_records:
Added `admins` (Full Table) stream for this test case.

2022-08-18 06:58 UTC, harshpatel4crest commented on tests/test_intercom_interrupted_sync.py
> +                            interrupted_bookmark_datetime = start_date_datetime
Updated interrupted test case to set intermediate state with the bookmark for currently syncing stream and updated assertion code to verify we are syncing records from the interrupted date for that stream.

2022-08-19 18:56 UTC, kspeer825 approved these changes

2022-09-06 19:38 UTC, RushiT0122 requested changes

2022-09-06 19:38 UTC, RushiT0122 commented on tests/test_intercom_automated_fields.py
> +                # Verify that all replicated records have unique primary key values.
Update the file name to `test_intercom_automatic_fields.py`

2022-09-06 19:38 UTC, RushiT0122 commented on tests/test_intercom_discovery.py
> +                self.assertEqual(len(actual_fields), len(set(actual_fields)), msg = "duplicates in the metadata entries retrieved")
Missing assertion `# Verify the stream names discovered were what we expect`

2022-09-06 19:38 UTC, RushiT0122 commented on tests/test_intercom_interrupted_sync.py
> +        """
For the integration tests where we sync twice, we usually follow the test structure like [the interrupted_sync test here](https://github.com/singer-io/tap-dixa/blob/main/tests/test_interrupted_sync.py). We have also developed `start_date` test in this suite on the similar lines. IMO, we should follow it consistently.

2022-09-07 11:41 UTC, savan-chovatiya commented on tests/test_intercom_automated_fields.py
> +                # Verify that all replicated records have unique primary key values.
Updated the file name as suggested.

2022-09-07 11:42 UTC, savan-chovatiya commented on tests/test_intercom_discovery.py
> +                self.assertEqual(len(actual_fields), len(set(actual_fields)), msg = "duplicates in the metadata entries retrieved")
Added missing assertion to verify stream names.

2022-09-07 11:43 UTC, savan-chovatiya commented on tests/test_intercom_interrupted_sync.py
> +        """
Thanks, I Updated the structure of the interrupted sync test as suggested.

2022-09-13 16:57 UTC, RushiT0122 commented on tests/test_intercom_start_date.py
>          # FIX CARD: https://jira.talendforge.org/browse/TDL-17035
State the expectations.

2022-09-13 18:15 UTC, RushiT0122 commented on tests/test_intercom_interrupted_sync.py
> +                        self.assertGreaterEqual(bookmark_final_state.get(expected_replication_key),full_sync_state.get('bookmarks')[bookmark_full_sync].get(expected_replication_key))
Also assertion is checking for equality. Tests should be designed to check greater than assertion. If not possible then should be mentioned likewise. This hold true for other tests as well where we compare bookmarks between 2 syncs.

2022-09-13 18:16 UTC, RushiT0122 commented on tests/test_intercom_interrupted_sync.py
> +                        self.assertGreaterEqual(bookmark_final_state.get(expected_replication_key),full_sync_state.get('bookmarks')[bookmark_full_sync].get(expected_replication_key))
Reduce the line length by moving parameters to next line, to make it readable.

2022-09-14 12:55 UTC, harshpatel4crest commented on tests/test_intercom_interrupted_sync.py
> +                        self.assertGreaterEqual(bookmark_final_state.get(expected_replication_key),full_sync_state.get('bookmarks')[bookmark_full_sync].get(expected_replication_key))
Updated the test case code by updating the variable name and reduced the length of code.

2022-09-14 12:55 UTC, harshpatel4crest commented on tests/test_intercom_start_date.py
>          # FIX CARD: https://jira.talendforge.org/browse/TDL-17035
Added docstring for the test_run function.

2022-09-14 13:30 UTC, RushiT0122 approved these changes

2022-09-26 08:20 UTC, merged