Use search query for contacts
singer-io/tap-intercom pull request #9
Opened 2020-10-13 19:43 UTC by dscoleman

# Description of change
Use Search Query endpoint for Contacts Stream, https://developers.intercom.com/intercom-api-reference/reference#search-for-contacts. 

Contacts now queried by `updated_at` with sort order ascending. Bookmarked by `updated_at`.

INFO START Syncing: contacts
INFO Stream: contacts, selected_fields: ['ios_os_version', 'os', 'external_id', 'android_last_seen_at', 'browser', 'location', 'name', 'android_device', 'role', 'social_profiles', 'ios_last_seen_at', 'last_replied_at', 'android_app_name', 'owner_id', 'type', 'marked_email_as_spam', 'ios_device', 'workspace_id', 'unsubscribed_from_emails', 'browser_version', 'android_sdk_version', 'companies', 'last_email_opened_at', 'last_seen_at', 'has_hard_bounced', 'ios_app_name', 'language_override', 'phone', 'android_os_version', 'created_at', 'last_email_clicked_at', 'browser_language', 'notes', 'ios_sdk_version', 'updated_at', 'android_app_version', 'last_contacted_at', 'id', 'custom_attributes', 'ios_app_version', 'signed_up_at', 'email', 'avatar', 'tags']
INFO contacts, initial max_bookmark_value 2020-10-08T00:00:00Z
INFO URL for Stream contacts: https://api.intercom.io/contacts/search?page=1&per_page=150
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.9356279373168945, "tags": {"endpoint": "contacts", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "contacts"}}
INFO Stream contacts, batch processed 50 records
INFO Write state for stream: contacts, value: 2020-10-09T08:19:53.000000Z
INFO Synced Stream: contacts, page: 1, records: 0 to 50
INFO URL for Stream contacts: https://api.intercom.io/contacts/search
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.9511361122131348, "tags": {"endpoint": "contacts", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "contacts"}}
INFO Stream contacts, batch processed 50 records
INFO Write state for stream: contacts, value: 2020-10-09T10:35:44.000000Z
INFO Synced Stream: contacts, page: 2, records: 50 to 100
INFO URL for Stream contacts: https://api.intercom.io/contacts/search
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 1.0927131175994873, "tags": {"endpoint": "contacts", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "contacts"}}
INFO Stream contacts, batch processed 50 records

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2020-10-19 19:08 UTC, dmosorast requested changes
Just one change requested to make the query inclusive.

2020-10-19 19:08 UTC, dmosorast commented on tap_intercom/streams.py
> +                'operator': '>',
This should probably be `>=` if available, to guard against edge cases where a bookmark is saved and more records come in with the same timestamp.

2020-10-19 19:08 UTC, dmosorast commented on tap_intercom/sync.py
> +            method=endpoint_config.get('method'),
Does this need a default value of `GET`? I guess the `perform` function will fall back to a get, but it's not super clear.

2020-10-19 19:08 UTC, dmosorast commented on tap_intercom/sync.py
> +            method=endpoint_config.get('method'),
Making this `endpoint_config.get('method','GET')` would be helpful for readers of the code.

2020-10-19 19:56 UTC, dmosorast commented on tap_intercom/streams.py
> +                'operator': '>',
Nm, Looking at the docs reveals that `>` refers to `>=`, I'm good to merge this then.

2020-10-19 19:56 UTC, dmosorast commented on tap_intercom/sync.py
> +            method=endpoint_config.get('method'),
Going to not block the merge on this point, since it looks like it'll work.

2020-10-19 19:57 UTC, dmosorast approved these changes

2020-10-19 19:57 UTC, merged

2025-07-16 17:42 UTC, luandy64 approved these changes